In [1]:
from mpmath import mp, matrix, eig, sqrt
import matplotlib.pyplot as plt
import numpy as np

In [2]:
mp.dps = 25  # Set precision

# ALL THE THINGS BELOW AREN'T INTEGRATED WITH mpmath yet

In [3]:
def tridiagonal_matrix(n, a, b, c):
    M = np.zeros((n, n))
    print(f'shape a = {a.shape}, shape b = {b.shape}, c shape = {c.shape}')
    for i in range(n):
        M[i][i] = b[i]
        if i > 0:
            M[i][i-1] = a[i]
        if i < n - 1:
            M[i][i+1] = c[i]

    return M


In [4]:
tridiagonal_matrix(20, np.ones((20, 1)), 2* np.ones((20, 1)),3* np.ones((20, 1)))

shape a = (20, 1), shape b = (20, 1), c shape = (20, 1)


/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_36562/1563754409.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i] = b[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_36562/1563754409.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i+1] = c[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_36562/1563754409.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i-1] = a[i]


array([[2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [5]:
def make_matrix_o(N, q, vn):
    
    h = vn[1]-vn[0]
    c = 2*q*np.cos(2* vn[1:-1]).reshape(len(vn)- 2,1)
    # c_bfore_restack = np.append(np.zeros((1,1)), 2*q*np.cos(2* vn[1:-1]).reshape(len(vn)- 2,1)).reshape(len(vn)- 1,1)
    # c = np.append(c_bfore_restack, np.zeros((1,1))).reshape(len(vn), 1)

    # zero at the ends
    # print(f'c = {c_bfore_restack}')
    # print(c_bfore_restack.shape)
    
    hm2 = np.ones((N,1))/(h*h)
    l = -2*hm2-c
    # print(f'l = {l.shape}')
    
    A = tridiagonal_matrix(N, hm2, l , hm2)

    # No boundary condition
   
    # print(A)
    return A


In [6]:
vn = np.linspace(-np.pi, np.pi, 10)
make_matrix_o(len(vn)-2, 1,vn)
# match with matlab

shape a = (8, 1), shape b = (8, 1), c shape = (8, 1)


/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_36562/1563754409.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i] = b[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_36562/1563754409.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i+1] = c[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_36562/1563754409.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i-1] = a[i]


array([[-4.45080429,  2.05175397,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 2.05175397, -2.2241227 ,  2.05175397,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  2.05175397, -3.10350794,  2.05175397,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  2.05175397, -5.63559682,  2.05175397,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  2.05175397, -5.63559682,
         2.05175397,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  2.05175397,
        -3.10350794,  2.05175397,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         2.05175397, -2.2241227 ,  2.05175397],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  2.05175397, -4.45080429]])

In [7]:
# make matrix e
from scipy import integrate

def mathieu_se(Ne, q, N):


    v = np.linspace(-np.pi, np.pi, N)
    A = make_matrix_o(N-2, q,v)




    # print(f'A= {A}')
    Draw, Sraw = np.linalg.eig(A) # (N-2, N-2)
    # print(f'Sraw = {Sraw}')
    # print(f'D = {Draw}')
    Dreal = [val.real for val in Draw]

    Denum = list(enumerate(Dreal))
    Didx = sorted(Denum, key=lambda x: x[1], reverse=True)
    idx = [idx for idx, val in Didx]


    S = Sraw[:, idx]
    
    # shifting could happen potentially because of stacking 

    # print(f'S after sorting = {S}')
    # se_1 = np.vstack((np.zeros((1,Ne)) ,S))
    # se = np.vstack((se_1, np.zeros((1,Ne))))

    se = np.vstack([np.zeros((1, S.shape[1])), S, np.zeros((1, S.shape[1]))])

    se = se[:, 1:2*Ne:2]
    # print(f'se = {se}')
    # # even 
    # # ce = mp.matrix(selected_cols_data)
    # # print(f'ce before norm = {ce}')
    
    # # print(f'ce[0, :])
    
    # Getting the correct sign of functions
    zidx = N // 2
    # h = v[1] - v[0]


    for j in range(Ne):
        diff = se[zidx + 1, j] - se[zidx , j]
        if diff < 0:
            se[:, j] = - se[:, j]
            

    # Normalisation 28.2.30
    # ce shape : (N, Ne)

    norm_cols = []
    h = v[1] -  v[0]

    # change it to normal matrix so that I can 
    # print(f'ce = {ce[:, 0]}')

    # Normalisation for ce_n
    for j in range(se.shape[1]):
        int_col = 0
        for i in range(1, se.shape[0]):
            int_f_ij = (0.5) * ((se[i - 1 , j])**2 + (se[i, j])**2) * h
            int_col += int_f_ij
        # int_col += (0.5) * ((ce[i - 1 , j])**2 + (ce[i, j])**2) * h
        traps_norm = sqrt(int_col / mp.pi) 
        norm_cols.append(traps_norm)
    
    # print(f'norm_cols = {len(norm_cols)}')
    # for k in range(ce.rows):
    for l in range(se.shape[1]):
        # print(norm_cols[l])
        se[:, l] = se[:, l] / norm_cols[l]
    
    # make this consistent with the implementation in matlab and REU

    # print(f'ce after norm= {ce}')



    # check the normalisation from Matlab 

    # print(f'ce = {ce[:, 0]}')
    
    # if q == 0:

    # did not get the values with both normalisation, check why


    # print(f'se shape = {se.shape}')


    return se # technically some of the normalisation gives me 0.9999999999999999999999999871 see if this is a problem



In [8]:
mathieu_se(3, 1, 10)

shape a = (8, 1), shape b = (8, 1), c shape = (8, 1)


/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_36562/1563754409.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i] = b[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_36562/1563754409.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i+1] = c[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_36562/1563754409.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i-1] = a[i]


array([[ 0.        ,  0.        ,  0.        ],
       [-0.49591307,  0.81461893,  1.15226677],
       [-1.12423055,  0.50926383, -0.82159327],
       [-0.83262789, -1.04893208,  0.32518887],
       [-0.2165795 , -0.47622247,  0.37618877],
       [ 0.2165795 ,  0.47622247, -0.37618877],
       [ 0.83262789,  1.04893208, -0.32518887],
       [ 1.12423055, -0.50926383,  0.82159327],
       [ 0.49591307, -0.81461893, -1.15226677],
       [ 0.        ,  0.        ,  0.        ]])

In [9]:
Ne = 3 # num of eigenvalues
Nq = 3  
q = np.linspace(0, 10, Nq)
N = 10  # discretisation of v
# mathieu_a(Ne, -100, N)
mathieu_se(Ne, 0.1, N)

shape a = (8, 1), shape b = (8, 1), c shape = (8, 1)


/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_36562/1563754409.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i] = b[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_36562/1563754409.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i+1] = c[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_36562/1563754409.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i-1] = a[i]


array([[ 0.        ,  0.        ,  0.        ],
       [-0.62624193,  0.97638027,  0.89749386],
       [-1.00115721,  0.35666225, -0.88071413],
       [-0.86563155, -0.88480205,  0.06233442],
       [-0.32586394, -0.62177082,  0.8154519 ],
       [ 0.32586394,  0.62177082, -0.8154519 ],
       [ 0.86563155,  0.88480205, -0.06233442],
       [ 1.00115721, -0.35666225,  0.88071413],
       [ 0.62624193, -0.97638027, -0.89749386],
       [ 0.        ,  0.        ,  0.        ]])

In [10]:
import numpy as np
import matplotlib.pyplot as plt

def write_mathieu_se_gvs(q=None):
    """
    This creates a file with golden values in columns used
    to test other impls of the Mathieu ce fcns.
    
    Parameters:
    q : float, optional - if not provided, will prompt for input
    """
    
    # Read q from user input if not provided
    if q is None:
        try:
            q = float(input("Enter q value: "))
        except ValueError:
            print("Invalid input for q")
            return
    
    print(f'q = {q:.6f}')
    
    N = 2500  # Number of v values
    # mathieu_ce only operates over the domain [-pi, pi]
    v = np.linspace(-np.pi, np.pi, N)
    Ne = 35    # Top order of fcn to request.
    
    # Compute fcn values
    # try:
    Ss = mathieu_se(Ne, q, N)  # GVs for different orders are
                                # arranged in columns.
    # except Exception as e:
    #     print(f'mathieu_ce threw exception: {str(e)}')
    #     return
    
    # # Make plots to check the fcns.
    # if False:  # Set to True to enable plotting
    #     plt.figure()
    #     leg = []
    #     for i in range(Ne):
    #         ce = Ss[:, i]   # Extract one order.
    #         plt.plot(v, ce)
    #         leg.append(str(i))
        
    #     plt.xlabel('v')
    #     plt.ylabel('ce')
    #     plt.legend(leg)
    #     plt.title('Golden values')
    #     plt.show()
    
    # Write GVs to a file along with the v value.
    filename = f'/Users/aliamy/Desktop/Mathieu/ScipyMathieuTesting/python_generated_gvs/python_mathieu_se_gvs_q{q:.6f}.csv'
    
    with open(filename, 'w') as fh:
        # First write q value to file.
        fh.write(f'{q:14.10f}\n')
        
        # Then write fcn values.
        for i in range(len(v)):
            # Write v value followed by all function values for this v
            line = f'{v[i]:14.10f}'
            for j in range(Ne):
                line += f', {Ss[i, j]}'
            line += '\n'
            fh.write(line)
    
    print(f'Golden values written to {filename}')

# Example usage:
if __name__ == "__main__":
    # You can call it with a specific q value:
    # write_mathieu_ce_gvs(2.5)
    
    # Or without arguments (will prompt for input):
    Q =  np.array([-100, -30, -10, -1, -0.1, -0.001, 0.001, 0.01, 0.1, 1, 10, 30, 100])
    # Q =  np.array([0.1])

    for q in Q:
        write_mathieu_se_gvs(q)

    # incorrect value written out
    

q = -100.000000
shape a = (2498, 1), shape b = (2498, 1), c shape = (2498, 1)


/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_36562/1563754409.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i] = b[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_36562/1563754409.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i+1] = c[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_36562/1563754409.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i-1] = a[i]


Golden values written to /Users/aliamy/Desktop/Mathieu/ScipyMathieuTesting/python_generated_gvs/python_mathieu_se_gvs_q-100.000000.csv
q = -30.000000
shape a = (2498, 1), shape b = (2498, 1), c shape = (2498, 1)
Golden values written to /Users/aliamy/Desktop/Mathieu/ScipyMathieuTesting/python_generated_gvs/python_mathieu_se_gvs_q-30.000000.csv
q = -10.000000
shape a = (2498, 1), shape b = (2498, 1), c shape = (2498, 1)
Golden values written to /Users/aliamy/Desktop/Mathieu/ScipyMathieuTesting/python_generated_gvs/python_mathieu_se_gvs_q-10.000000.csv
q = -1.000000
shape a = (2498, 1), shape b = (2498, 1), c shape = (2498, 1)
Golden values written to /Users/aliamy/Desktop/Mathieu/ScipyMathieuTesting/python_generated_gvs/python_mathieu_se_gvs_q-1.000000.csv
q = -0.100000
shape a = (2498, 1), shape b = (2498, 1), c shape = (2498, 1)
Golden values written to /Users/aliamy/Desktop/Mathieu/ScipyMathieuTesting/python_generated_gvs/python_mathieu_se_gvs_q-0.100000.csv
q = -0.001000
shape a = (