In [52]:
from mpmath import mp, matrix, eig, sqrt
import matplotlib.pyplot as plt
import numpy as np

In [53]:
mp.dps = 25  # Set precision

# ALL THE THINGS BELOW AREN'T INTEGRATED WITH mpmath yet

In [54]:
# numpy 

def tridiagonal_matrix_np(n, a, b, c):
    M = np.zeros((n, n))
    # print(f'shape a = {a.shape}, shape b = {b.shape}, c shape = {c.shape}')
    for i in range(n):
        M[i][i] = b[i]
        if i > 0:
            M[i][i-1] = a[i]
        if i < n - 1:
            M[i][i+1] = c[i]

    return M


In [55]:
tridiagonal_matrix_np(20, np.ones((20, 1)), 2* np.ones((20, 1)),3* np.ones((20, 1)))

/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_60287/150820386.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i] = b[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_60287/150820386.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i+1] = c[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_60287/150820386.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i-1] = a[i]


array([[2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [56]:
# numpy 
def make_matrix_e_np(q, vn):
    N = len(vn)
    h = vn[1]-vn[0]
    c = 2*q*np.cos(2* vn).reshape((len(vn),1))
    hm2 = np.ones((N,1))/(h*h)
    
    
    A = tridiagonal_matrix_np(N, hm2, -2*hm2-c, hm2)
    A[0,1] = 2*hm2[0]
    A[N-1,N-2] = 2*hm2[0]
    print(A)
    return A

In [57]:
# numpy
vn = np.linspace(-np.pi, np.pi, 10)
make_matrix_e_np(-100.0,vn)

[[ 195.89649206    4.10350794    0.            0.            0.
     0.            0.            0.            0.            0.        ]
 [   2.05175397   30.6261276     2.05175397    0.            0.
     0.            0.            0.            0.            0.        ]
 [   0.            2.05175397 -192.04203209    2.05175397    0.
     0.            0.            0.            0.            0.        ]
 [   0.            0.            2.05175397 -104.10350794    2.05175397
     0.            0.            0.            0.            0.        ]
 [   0.            0.            0.            2.05175397  149.10538069
     2.05175397    0.            0.            0.            0.        ]
 [   0.            0.            0.            0.            2.05175397
   149.10538069    2.05175397    0.            0.            0.        ]
 [   0.            0.            0.            0.            0.
     2.05175397 -104.10350794    2.05175397    0.            0.        ]
 [   0.          

/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_60287/150820386.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i] = b[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_60287/150820386.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i+1] = c[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_60287/150820386.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i-1] = a[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcv

array([[ 195.89649206,    4.10350794,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ],
       [   2.05175397,   30.6261276 ,    2.05175397,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    2.05175397, -192.04203209,    2.05175397,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    0.        ,    2.05175397, -104.10350794,
           2.05175397,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    0.        ,    0.        ,    2.05175397,
         149.10538069,    2.05175397,    0.        ,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    0.        ,    0.        ,    0.        ,
           2.05175397,  149.10538069,    2.05175397,    0

In [58]:
# mpmath 
def tridiagonal_matrix(n, a, b, c):
    M = matrix(n, n)
    for i in range(n):
        M[i, i] = b[i]
        if i > 0:
            M[i, i-1] = a[i]
        if i < n - 1:
            M[i, i+1] = c[i]
    return M

In [59]:
# mpmath
def make_matrix_e(q, vn):
    N = len(vn)
    h = vn[1]-vn[0]
    c = 2*mp.mpf(q)*matrix([mp.cos(mp.mpf(2*x)) for x in vn])
    hm2 = matrix(mp.ones(N,1))/(h*h)
    
    A = tridiagonal_matrix(N, hm2, -2*hm2-c, hm2)
    A[0,1] = 2*hm2[0]
    A[N-1,N-2] = 2*hm2[0]
    return A

In [60]:
vn = mp.linspace(-mp.pi, mp.pi, 10)
make_matrix_e(-100.0,vn)

matrix(
[['195.8964920624853202565229', '4.103507937514679743477118', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
 ['2.051753968757339871738559', '30.62612759587139002686622', '2.051753968757339871738559', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
 ['0.0', '2.051753968757339871738559', '-192.042032094696356554299', '2.051753968757339871738559', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0'],
 ['0.0', '0.0', '2.051753968757339871738559', '-104.1035079375146797434771', '2.051753968757339871738559', '0.0', '0.0', '0.0', '0.0', '0.0'],
 ['0.0', '0.0', '0.0', '2.051753968757339871738559', '149.1053806862809272970014', '2.051753968757339871738559', '0.0', '0.0', '0.0', '0.0'],
 ['0.0', '0.0', '0.0', '0.0', '2.051753968757339871738559', '149.1053806862809272970014', '2.051753968757339871738559', '0.0', '0.0', '0.0'],
 ['0.0', '0.0', '0.0', '0.0', '0.0', '2.051753968757339871738559', '-104.1035079375146797434771', '2.051753968757339871738559', '0.0', '0.0'],
 ['0.0', '0.0', '0.

In [75]:
# numpy
# make matrix e

def mathieu_a(Ne, q, N):
    v = mp.linspace(-np.pi, np.pi, N)
    A = make_matrix_e(q,v)
    Draw, _ = eig(A)
    # print(len(Draw))
    Dreal = [val.real for val in Draw]
    Denum = list(enumerate(Dreal))
    Didx = sorted(Denum, key=lambda x: x[1], reverse=True)
    idx = [idx for idx, val in Didx]
    D = matrix(2*Ne, 1)
    for i in range(0,Ne):
        # Extract only even order eigenvalues.
        D[i] = -Dreal[idx[2*i]]

    return v, D

def mathieu_ce_np(Ne, q, N):
    
    v = np.linspace(-np.pi, np.pi, N)
    A = make_matrix_e_np(q,v)

    # print(f'A= {A}')
    Draw, Sraw = np.linalg.eig(A)
    # print(f'Sraw = {Sraw}')
    # print(f'D = {Draw}')
    Dreal = [val.real for val in Draw]

    Denum = list(enumerate(Dreal))
    Didx = sorted(Denum, key=lambda x: x[1], reverse=True)
    idx = [idx for idx, val in Didx]


    S = Sraw[:, idx]
    ce = S[:, :2*Ne:2]
    print(f'ce = {ce}')
    
    # Normalisation for the values when v = 0
    zidx = N // 2
    

    for j in range(Ne):
        if ce[zidx, j] < 0:
            ce[:, j] = - ce[:, j]
            

    # Normalisation 28.2.30
    # ce shape : (N, Ne)

    norm_cols = []
    h = v[1] -  v[0]


    # Normalisation for ce_n
    for j in range(ce.shape[1]):
        int_col = 0
        for i in range(1, ce.shape[0]):
            int_f_ij = (0.5) * ((ce[i - 1 , j])**2 + (ce[i, j])**2) * h
            int_col += int_f_ij
        traps_norm = sqrt(int_col / mp.pi) 
        norm_cols.append(traps_norm)
    
    
    for l in range(ce.shape[1]):
        ce[:, l] = ce[:, l] / norm_cols[l]
    
   

    # print(f'ce after norm= {ce}')



    return ce 


In [76]:
# numpy

Ne = 3 # num of eigenvalues
Nq = 3  
q = np.linspace(0, 10, Nq)
N = 10  # discretisation of v
# mathieu_a(Ne, -100, N)
mathieu_ce_np(Ne, 1, N)

[[-6.10350794  4.10350794  0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 2.05175397 -4.45080429  2.05175397  0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          2.05175397 -2.2241227   2.05175397  0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          2.05175397 -3.10350794  2.05175397  0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          2.05175397 -5.63559682  2.05175397
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          2.05175397 -5.63559682
   2.05175397  0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          2.05175397
  -3.10350794  2.05175397  0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   2.05175397 -2.2241227   2.05175397  0.        ]
 [ 0.          0.          0.          0

/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_60287/150820386.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i] = b[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_60287/150820386.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i+1] = c[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_60287/150820386.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i-1] = a[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcv

array([[ 0.35126076, -0.76143857,  1.04038613],
       [ 0.56754323, -0.81241288,  0.61415358],
       [ 1.02557421, -0.31775589, -0.81000575],
       [ 0.80744262,  0.73515874, -0.03893684],
       [ 0.40303421,  0.81158104,  0.82096793],
       [ 0.40303421,  0.81158104,  0.82096793],
       [ 0.80744262,  0.73515874, -0.03893684],
       [ 1.02557421, -0.31775589, -0.81000575],
       [ 0.56754323, -0.81241288,  0.61415358],
       [ 0.35126076, -0.76143857,  1.04038613]])

In [79]:
def extract_single_column(Sraw, col_idx):
    """Extract a single column from mpmath matrix"""
    rows = Sraw.rows
    S = mp.matrix(rows, 1)
    for i in range(rows):
        S[i, 0] = Sraw[i, col_idx]
    return S

def extract_columns(Sraw, idx):
    """Extract multiple columns from mpmath matrix using list of indices"""
    rows = Sraw.rows
    if isinstance(idx, int):
        # Single column case
        return extract_single_column(Sraw, idx)
    
    # Multiple columns case
    cols = len(idx)
    S = mp.matrix(rows, cols)
    for i in range(rows):
        for j, col_idx in enumerate(idx):
            S[i, j] = Sraw[i, col_idx]
    return S

In [80]:
def mpmath_to_numpy_high_precision(S):
    """Convert mpmath matrix to numpy array with extended precision"""
    rows, cols = S.rows, S.cols
    # Use numpy's longdouble for extended precision
    numpy_array = np.array([[np.longdouble(str(S[i,j])) for j in range(cols)] for i in range(rows)])
    return numpy_array

In [83]:
def mpmath_slice_even_2Ne_explicit(S, Ne):
    """More explicit version showing the logic"""
    rows = S.rows
    cols_needed = []
    
    # Generate column indices: start=0, stop=2*Ne, step=2
    col = 0
    while col < 2*Ne and col < S.cols:
        cols_needed.append(col)
        col += 2
    
    # Create new matrix
    if not cols_needed:
        return mp.matrix(rows, 0)
    
    ce = mp.matrix(rows, len(cols_needed))
    for i in range(rows):
        for j, col_idx in enumerate(cols_needed):
            ce[i, j] = S[i, col_idx]
    
    return ce

In [86]:
def mpmath_column_sign_fix(ce, zidx, Ne):
    """
    mpmath equivalent of:
    for j in range(Ne):
        if ce[zidx, j] < 0:
            ce[:, j] = - ce[:, j]
    
    Args:
        ce: mpmath matrix
        zidx: row index to check for sign
        Ne: number of columns to process
    """
    for j in range(Ne):
        if ce[zidx, j] < 0:
            # Flip the sign of entire column j
            for i in range(ce.rows):
                ce[i, j] = -ce[i, j]

In [ ]:
def normalize_mpmath_matrix_explicit(ce, h):
    """
    More explicit version ensuring all operations use mpmath
    """
    norm_cols = []
    
    # Convert h to mpmath if it isn't already
    h_mp = mp.mpf(h)
    
    # First loop: calculate normalization factors
    for j in range(ce.cols):
        int_col = mp.mpf(0)
        for i in range(1, ce.rows):
            # Ensure all operations are in mpmath
            term1 = ce[i - 1, j] ** 2
            term2 = ce[i, j] ** 2
            int_f_ij = mp.mpf(0.5) * (term1 + term2) * h_mp
            int_col += int_f_ij
        traps_norm = mp.sqrt(int_col / mp.pi) 
        norm_cols.append(traps_norm)
    
    # Second loop: normalize each column
    for l in range(ce.cols):
        norm_factor = norm_cols[l]
        for i in range(ce.rows):
            ce[i, l] = ce[i, l] / norm_factor
            


In [117]:
# numpy
def mathieu_ce_np(Ne, q, N):
    
    v = np.linspace(-np.pi, np.pi, N)
    A = make_matrix_e_np(q,v)

    # print(f'A= {A}')
    Draw, Sraw = np.linalg.eig(A)
    print(type(Draw), type(Sraw))
    
    Dreal = [val.real for val in Draw]

    Denum = list(enumerate(Dreal))
    Didx = sorted(Denum, key=lambda x: x[1], reverse=True)
    idx = [idx for idx, val in Didx]

    
    S = Sraw[:, idx]
    # print(f'S np = {S}')

    S = Sraw[:, idx]

    ce = S[:, :2*Ne:2]
    
    # Normalisation for the values when v = 0
    zidx = N // 2
    

    for j in range(Ne):
        if ce[zidx, j] < 0:
            ce[:, j] = - ce[:, j]

    # Normalisation 28.2.30
    # ce shape : (N, Ne)

    norm_cols = []
    h = v[1] -  v[0]

    # Normalisation for ce_n
    for j in range(ce.shape[1]):
        int_col = 0
        for i in range(1, ce.shape[0]):
            int_f_ij = (0.5) * ((ce[i - 1 , j])**2 + (ce[i, j])**2) * h
            int_col += int_f_ij
        print(f'int_col = {int_col}')
        traps_norm = np.sqrt(int_col / np.pi) 
        print(f'traps_norm = {traps_norm}')
        norm_cols.append(float(traps_norm))
    
    print(norm_cols)
    for l in range(ce.shape[1]):
        ce[:, l] = ce[:, l] / norm_cols[l]
    
    print(f'ce np = {ce}')
    

    # print(f'ce after norm= {ce}')



    return ce 



In [118]:
Ne = 3 # num of eigenvalues
Nq = 3  
q = np.linspace(0, 10, Nq)
N = 10  # discretisation of v
# mathieu_a(Ne, -100, N)
mathieu_ce_np(Ne, 1, N)

[[-6.10350794  4.10350794  0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 2.05175397 -4.45080429  2.05175397  0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          2.05175397 -2.2241227   2.05175397  0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          2.05175397 -3.10350794  2.05175397  0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          2.05175397 -5.63559682  2.05175397
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          2.05175397 -5.63559682
   2.05175397  0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          2.05175397
  -3.10350794  2.05175397  0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   2.05175397 -2.2241227   2.05175397  0.        ]
 [ 0.          0.          0.          0

/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_60287/150820386.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i] = b[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_60287/150820386.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i+1] = c[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_60287/150820386.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i-1] = a[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcv

array([[ 0.35126076, -0.76143857,  1.04038613],
       [ 0.56754323, -0.81241288,  0.61415358],
       [ 1.02557421, -0.31775589, -0.81000575],
       [ 0.80744262,  0.73515874, -0.03893684],
       [ 0.40303421,  0.81158104,  0.82096793],
       [ 0.40303421,  0.81158104,  0.82096793],
       [ 0.80744262,  0.73515874, -0.03893684],
       [ 1.02557421, -0.31775589, -0.81000575],
       [ 0.56754323, -0.81241288,  0.61415358],
       [ 0.35126076, -0.76143857,  1.04038613]])

In [ ]:
def mathieu_ce(Ne, q, N):
    
    v = mp.linspace(-mp.pi, mp.pi, N)
    A = make_matrix_e(q,v)

    # print(f'A= {A}')
    Draw, Sraw = eig(A)
    
    Dreal = [val.real for val in Draw]

    Denum = list(enumerate(Dreal))
    Didx = sorted(Denum, key=lambda x: x[1], reverse=True)
    idx = [idx for idx, val in Didx]

    S = extract_columns(Sraw, idx)
    ce = mpmath_slice_even_2Ne_explicit(S, Ne)
    # print(f'S mp math = {S}')
    

    # Normalisation for the values when v = 0
    zidx = N // 2
    
    mpmath_column_sign_fix(ce, zidx, Ne)
    

    # Normalisation 28.2.30
    # ce shape : (N, Ne)

    h = v[1] -  v[0]

    normalize_mpmath_matrix_explicit(ce, h)
    print(f'ce mp = {ce}')





    return ce 

In [120]:
Ne = 3 # num of eigenvalues
Nq = 3  
q = mp.linspace(0, 10, Nq)
N = 10  # discretisation of v
# mathieu_a(Ne, -100, N)
mathieu_ce(Ne, 1, N)

<class 'list'> <class 'mpmath.matrices.matrices.matrix'>
ce mp = [0.3512607610384413396789781  -0.7614385697839900401664353     1.040386132751790656412993]
[ 0.567543226070073265355858  -0.8124128793536290614317911    0.6141535806725906895002767]
[  1.02557421339602252523505  -0.3177558926666375204806737   -0.8100057494789934620350831]
[0.8074426207870514552240034   0.7351587415895630938955962  -0.03893684076631657972199429]
[0.4030342074476913279436879   0.8115810390978093486244186    0.8209679256694715382252918]
[0.4030342074476913279436881   0.8115810390978093486244183    0.8209679256694715382252914]
[ 0.807442620787051455224004   0.7351587415895630938955953  -0.03893684076631657972199459]
[ 1.025574213396022525235051  -0.3177558926666375204806736   -0.8100057494789934620350829]
[0.5675432260700732653558584  -0.8124128793536290614317902    0.6141535806725906895002767]
[0.3512607610384413396789784  -0.7614385697839900401664344     1.040386132751790656412993]


matrix(
[['0.3512607610384413396789781', '-0.7614385697839900401664353', '1.040386132751790656412993'],
 ['0.567543226070073265355858', '-0.8124128793536290614317911', '0.6141535806725906895002767'],
 ['1.02557421339602252523505', '-0.3177558926666375204806737', '-0.8100057494789934620350831'],
 ['0.8074426207870514552240034', '0.7351587415895630938955962', '-0.03893684076631657972199429'],
 ['0.4030342074476913279436879', '0.8115810390978093486244186', '0.8209679256694715382252918'],
 ['0.4030342074476913279436881', '0.8115810390978093486244183', '0.8209679256694715382252914'],
 ['0.807442620787051455224004', '0.7351587415895630938955953', '-0.03893684076631657972199459'],
 ['1.025574213396022525235051', '-0.3177558926666375204806736', '-0.8100057494789934620350829'],
 ['0.5675432260700732653558584', '-0.8124128793536290614317902', '0.6141535806725906895002767'],
 ['0.3512607610384413396789784', '-0.7614385697839900401664344', '1.040386132751790656412993']])

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

def write_mathieu_ce_gvs(q=None):
    """
    This creates a file with golden values in columns used
    to test other impls of the Mathieu ce fcns.
    
    Parameters:
    q : float, optional - if not provided, will prompt for input
    """
    
    if q is None:
        try:
            q = float(input("Enter q value: "))
        except ValueError:
            print("Invalid input for q")
            return
    
    print(f'q = {q:.6f}')
    
    N = 2500  # Number of v values
    # mathieu_ce only operates over the domain [-pi, pi]
    v = mp.linspace(-mp.pi, mp.pi, N)
    Ne = 35    # Top order of fcn to request.
    
    
    Ss = mathieu_ce(Ne, q, N)  # GVs for different orders are
                                # arranged in columns.
   
    
    # Write GVs to a file along with the v value.
    filename = f'/Users/aliamy/Desktop/Mathieu/ScipyMathieuTesting/python_generated_gvs/python_mathieu_ce_gvs_q{q:.6f}.csv'
    
    with open(filename, 'w') as fh:
        # First write q value to file.
        fh.write(f'{q:14.10f}\n')
        
        # Then write fcn values.
        for i in range(len(v)):
            # Write v value followed by all function values for this v
            line = f'{v[i]}'
            for j in range(Ne):
                line += f', {Ss[i, j]}'
            line += '\n'
            fh.write(line)
    
    print(f'Golden values written to {filename}')

# Example usage:
if __name__ == "__main__":
    
    Q =  np.array([-100, -30, -10, -1, -0.1, -0.001, 0.001, 0.01, 0.1, 1, 10, 30, 100])
    # Q =  np.array([ 1])

    for q in Q:
        write_mathieu_ce_gvs(q)

    

q = -100.000000
