In [1]:
from mpmath import mp, matrix, eig, sqrt
import matplotlib.pyplot as plt
import numpy as np

In [2]:
mp.dps = 25  # Set precision

# ALL THE THINGS BELOW AREN'T INTEGRATED WITH mpmath yet

In [3]:
# numpy
def tridiagonal_matrix_np(n, a, b, c):
    M = np.zeros((n, n))
    # print(f'shape a = {a.shape}, shape b = {b.shape}, c shape = {c.shape}')
    for i in range(n):
        M[i][i] = b[i]
        if i > 0:
            M[i][i-1] = a[i]
        if i < n - 1:
            M[i][i+1] = c[i]

    return M


In [4]:
tridiagonal_matrix_np(20, np.ones((20, 1)), 2* np.ones((20, 1)),3* np.ones((20, 1)))

/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_1031/1481670576.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i] = b[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_1031/1481670576.py:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i+1] = c[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_1031/1481670576.py:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i-1] = a[i]


array([[2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [5]:
# numpy

def make_matrix_o_np(N, q, vn):
    
    h = vn[1]-vn[0]
    c = 2*q*np.cos(2* vn[1:-1]).reshape(len(vn)- 2,1)
    
    
    hm2 = np.ones((N,1))/(h*h)
    l = -2*hm2-c
   
    
    A = tridiagonal_matrix_np(N, hm2, l , hm2)

    # No boundary condition
   
    # print(A)
    return A


In [6]:

N = 2
print(len(range(1, N+1)))

2


In [7]:
from scipy.linalg import toeplitz

def fourier_diff(N, q):
    h = 2 * np.pi / N
    v = h * (np.array(range(1, N+1)))

    col = np.array([0])
    for j in range(1, N):
        col = np.append(col, 0.5 * (-1)** j * (1/ np.tan(j * h / 2)) )

    col_t = np.array([1])
    for k in range(N, 1, -1):
        col_t = np.append(col_t, 0.5 * (-1)** k * (1/ np.tan(k * h / 2)) )

    cos_col = np.cos(v)
    print(cos_col.shape)
    return toeplitz(col, col_t) + 2* q * np.diag(cos_col)

print(fourier_diff(4, 2))


(4,)
[[ 2.44929360e-16 -4.08280984e+15  5.00000000e-01  3.06161700e-17]
 [-5.00000000e-01 -4.00000000e+00 -4.08280984e+15  5.00000000e-01]
 [ 3.06161700e-17 -5.00000000e-01 -7.34788079e-16 -4.08280984e+15]
 [ 5.00000000e-01  3.06161700e-17 -5.00000000e-01  4.00000000e+00]]


In [8]:
vn = np.linspace(-np.pi, np.pi, 10)
make_matrix_o_np(len(vn)-2, 1,vn)
# match with matlab

/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_1031/1481670576.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i] = b[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_1031/1481670576.py:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i+1] = c[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_1031/1481670576.py:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i-1] = a[i]


array([[-4.45080429,  2.05175397,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 2.05175397, -2.2241227 ,  2.05175397,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  2.05175397, -3.10350794,  2.05175397,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  2.05175397, -5.63559682,  2.05175397,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  2.05175397, -5.63559682,
         2.05175397,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  2.05175397,
        -3.10350794,  2.05175397,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         2.05175397, -2.2241227 ,  2.05175397],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  2.05175397, -4.45080429]])

In [9]:
# numpy
from scipy import integrate

def mathieu_se_np(Ne, q, N):


    v = np.linspace(0, 2 * np.pi, N)
    A = make_matrix_o_np(N-2, q,v)

    # A = fourier_diff(N, q)


    # print(f'A= {A}')
    Draw, Sraw = np.linalg.eig(A) # (N-2, N-2)
    # print(f'Sraw = {Sraw}')
    # print(f'D = {Draw}')
    Dreal = [val.real for val in Draw]

    Denum = list(enumerate(Dreal))
    Didx = sorted(Denum, key=lambda x: x[1], reverse=True)
    idx = [idx for idx, val in Didx]


    S = Sraw[:, idx]
    
    

    se = np.vstack([np.zeros((1, S.shape[1])), S, np.zeros((1, S.shape[1]))])

    se = se[:, 1:2*Ne:2]
    
    # Getting the correct sign of functions
    zidx = N // 2
    # h = v[1] - v[0]


    for j in range(Ne):
        diff = se[zidx + 1, j] - se[zidx , j]
        if diff < 0:
            se[:, j] = - se[:, j]
            

    # Normalisation 28.2.30
    # ce shape : (N, Ne)

    norm_cols = []
    h = v[1] -  v[0]

   
    # Normalisation for ce_n
    for j in range(se.shape[1]):
        int_col = 0
        for i in range(1, se.shape[0]):
            int_f_ij = (0.5) * ((se[i - 1 , j])**2 + (se[i, j])**2) * h
            int_col += int_f_ij
        # int_col += (0.5) * ((ce[i - 1 , j])**2 + (ce[i, j])**2) * h
        traps_norm = sqrt(int_col / mp.pi) 
        norm_cols.append(traps_norm)
    
    
    for l in range(se.shape[1]):
        # print(norm_cols[l])
        se[:, l] = se[:, l] / norm_cols[l]
    
    print(f'se after norm = {se}')



    return se 


In [10]:
# mpmath 
def tridiagonal_matrix(n, a, b, c):
    M = matrix(n, n)
    for i in range(n):
        M[i, i] = b[i]
        if i > 0:
            M[i, i-1] = a[i]
        if i < n - 1:
            M[i, i+1] = c[i]
    return M

In [11]:
def get_middle_elements(c):
    """
    Remove first and last elements from matrix
    Input: (n, 1) matrix
    Output: (n-2, 1) matrix
    
    Equivalent to c[1:-1] in NumPy
    """
    n = c.rows
    if n < 3:
        raise ValueError(f"Matrix must have at least 3 rows, got {n}")
    
    # Create new matrix of size (n-2, 1)
    middle = mp.matrix(n - 2, 1)
    for i in range(n - 2):
        middle[i, 0] = c[i + 1, 0]  # Start from index 1, skip index 0
    
    return middle

In [12]:
# mp math
def make_matrix_o(N, q, vn):

    h = vn[1]-vn[0]
    c = 2*mp.mpf(q)*matrix([mp.cos(mp.mpf(2*x)) for x in vn])
    c = get_middle_elements(c)
    


    hm2 = matrix(mp.ones(N,1))/(h*h)

    
    l = -2*hm2-c


    A = tridiagonal_matrix(N, hm2, l , hm2)

    # No boundary condition

    # print(A)
    return A


In [13]:
# vn = mp.linspace(-mp.pi, mp.pi, 10)
# make_matrix_o(len(vn)-2, 1,vn)

In [14]:
def extract_single_column(Sraw, col_idx):
    """Extract a single column from mpmath matrix"""
    rows = Sraw.rows
    S = mp.matrix(rows, 1)
    for i in range(rows):
        S[i, 0] = Sraw[i, col_idx]
    return S

def extract_columns(Sraw, idx):
    """Extract multiple columns from mpmath matrix using list of indices"""
    rows = Sraw.rows
    if isinstance(idx, int):
        # Single column case
        return extract_single_column(Sraw, idx)
    
    # Multiple columns case
    cols = len(idx)
    S = mp.matrix(rows, cols)
    for i in range(rows):
        for j, col_idx in enumerate(idx):
            S[i, j] = Sraw[i, col_idx]
    return S

In [15]:
def mpmath_slice_odd_2Ne_explicit(S, Ne):
    """
    Extract odd columns from mpmath matrix
    Equivalent to S[:, 1:2*Ne:2] in NumPy
    Gets columns 1, 3, 5, 7, ... up to 2*Ne-1
    
    Args:
        S: mpmath matrix
        Ne: parameter to determine range (extracts up to column 2*Ne-1)
    
    Returns:
        mpmath matrix with odd columns
    """
    rows = S.rows
    cols_needed = []
    
    # Generate column indices: start=1, stop=2*Ne, step=2
    col = 1  # Start at 1 instead of 0 for odd columns
    while col < 2*Ne and col < S.cols:
        cols_needed.append(col)
        col += 2  # Step by 2 to get odd indices
    
    # Create new matrix
    if not cols_needed:
        return mp.matrix(rows, 0)
    
    co = mp.matrix(rows, len(cols_needed))  # co for "columns odd"
    for i in range(rows):
        for j, col_idx in enumerate(cols_needed):
            co[i, j] = S[i, col_idx]
    
    return co

In [16]:
def mpmath_column_sign_fix(se, zidx, Ne):
    """
    mpmath equivalent of:
    for j in range(Ne):
        if ce[zidx, j] < 0:
            ce[:, j] = - ce[:, j]
    
    Args:
        ce: mpmath matrix
        zidx: row index to check for sign
        Ne: number of columns to process
    """
    for j in range(Ne):
        diff = se[zidx + 1, j] - se[zidx , j]
        if diff < 0:
            # Flip the sign of entire column j
            for i in range(se.rows):
                se[i, j] = -se[i, j]

In [17]:
def normalize_mpmath_matrix_explicit(ce, h):
    """
    More explicit version ensuring all operations use mpmath
    """
    norm_cols = []
    
    # Convert h to mpmath if it isn't already
    h_mp = mp.mpf(h)
    
    # First loop: calculate normalization factors
    for j in range(ce.cols):
        int_col = mp.mpf(0)
        for i in range(1, ce.rows):
            # Ensure all operations are in mpmath
            term1 = ce[i - 1, j] ** 2
            term2 = ce[i, j] ** 2
            int_f_ij = mp.mpf(0.5) * (term1 + term2) * h_mp
            int_col += int_f_ij
        traps_norm = mp.sqrt(int_col / mp.pi) 
        norm_cols.append(traps_norm)
    
    # Second loop: normalize each column
    for l in range(ce.cols):
        norm_factor = norm_cols[l]
        for i in range(ce.rows):
            ce[i, l] = ce[i, l] / norm_factor
            

In [18]:
def add_zero_rows(S):
    """
    Add rows of zeros at top and bottom
    Input: (n, m) matrix
    Output: (n+2, m) matrix
    """
    n, m = S.rows, S.cols
    
    # Create new matrix of size (n+2, m)
    extended = mp.matrix(n + 2, m)
    
    # Copy original matrix to middle rows (rows 1 through n)
    for i in range(n):
        for j in range(m):
            extended[i + 1, j] = S[i, j]
    
    # First and last rows are already zeros by default
    return extended

In [19]:
# mp math


def mathieu_se(Ne, q, N):


    v = mp.linspace(-mp.pi, mp.pi, N)
    A = make_matrix_o(N-2, q,v)

    Draw, Sraw = eig(A) # (N-2, N-2)
   
    Dreal = [val.real for val in Draw]

    Denum = list(enumerate(Dreal))
    Didx = sorted(Denum, key=lambda x: x[1], reverse=True)
    idx = [idx for idx, val in Didx]

    S = extract_columns(Sraw, idx)
    
    se = add_zero_rows(S)

    se = mpmath_slice_odd_2Ne_explicit(se, Ne)
    
    # Getting the correct sign of functions
    zidx = N // 2

    mpmath_column_sign_fix(se, zidx, Ne)
    

    # Normalisation 28.2.30
    # ce shape : (N, Ne)

    h = v[1] -  v[0]

    

    # Normalisation for ce_n
    normalize_mpmath_matrix_explicit(se, h)



    return se # technically some of the normalisation gives me 0.9999999999999999999999999871 see if this is a problem



In [20]:
# mathieu_se(3, 1, 10)

In [21]:
# mathieu_se_np(3, 1, 10)

In [22]:
# Ne = 3 # num of eigenvalues
# Nq = 3  
# q = np.linspace(0, 10, Nq)
# N = 10  # discretisation of v
# # mathieu_a(Ne, -100, N)
# mathieu_se(Ne, 0.1, N)

In [23]:
# mathieu_se_np(Ne, 0.1, N)

In [24]:
import numpy as np
import matplotlib.pyplot as plt

def write_mathieu_se_gvs(q=None):
    """
    This creates a file with golden values in columns used
    to test other impls of the Mathieu ce fcns.
    
    Parameters:
    q : float, optional - if not provided, will prompt for input
    """
    
    # Read q from user input if not provided
    if q is None:
        try:
            q = float(input("Enter q value: "))
        except ValueError:
            print("Invalid input for q")
            return
    
    print(f'q = {q:.6f}')
    
    N = 2500  # Number of v values
    # mathieu_ce only operates over the domain [-pi, pi]
    v = np.linspace(-np.pi,  np.pi, N)
    Ne = 35    # Top order of fcn to request.
    
    # Compute fcn values
    # try:
    Ss = mathieu_se_np(Ne, q, N)  # GVs for different orders are
                                # arranged in columns.
    
    
    # Write GVs to a file along with the v value.
    filename = f'/Users/aliamy/Desktop/Mathieu/ScipyMathieuTesting/python_generated_gvs/python_mathieu_se_gvs_q{q:.6f}.csv'
    
    with open(filename, 'w') as fh:
        # First write q value to file.
        fh.write(f'{q:14.10f}\n')
        
        # Then write fcn values.
        for i in range(len(v)):
            # Write v value followed by all function values for this v
            line = f'{v[i]}'
            for j in range(Ne):
                line += f', {Ss[i, j]}'
            line += '\n'
            fh.write(line)
    
    print(f'Golden values written to {filename}')

# Example usage:
if __name__ == "__main__":
    
    
    # Or without arguments (will prompt for input):
    Q =  np.array([-100, -30, -10, -1, -0.1, -0.001, 0.001, 0.01, 0.1, 1, 10, 30, 100])
    # Q =  np.array([0.1])

    for q in Q:
        write_mathieu_se_gvs(q)

    # incorrect value written out
    

q = -100.000000


/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_1031/1481670576.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i] = b[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_1031/1481670576.py:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i+1] = c[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_1031/1481670576.py:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i-1] = a[i]


se after norm = [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-4.63976016e-07  7.78140113e-04 -3.44219045e-02 ... -8.63341051e-02
   8.87563954e-02 -9.11813026e-02]
 [-9.27779815e-07  1.55599139e-03 -6.88147767e-02 ... -1.71962543e-01
   1.76749927e-01 -1.81539319e-01]
 ...
 [ 1.23522497e-01 -5.05089734e-05  7.71874559e-02 ...  1.71962543e-01
  -1.76749927e-01  1.81539319e-01]
 [ 6.17727132e-02 -2.52591746e-05  3.86100103e-02 ...  8.63341051e-02
  -8.87563954e-02  9.11813026e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]
Golden values written to /Users/aliamy/Desktop/Mathieu/ScipyMathieuTesting/python_generated_gvs/python_mathieu_se_gvs_q-100.000000.csv
q = -30.000000
se after norm = [[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [-0.01923082  0.01922704 -0.02172692 ... -0.08398589  0.08646016
  -0.08893553]
 [-0.03845781  0.03845024 -0