In [28]:
from mpmath import mp, matrix, eig, sqrt
import matplotlib.pyplot as plt
import numpy as np

In [29]:
mp.dps = 25  # Set precision

# ALL THE THINGS BELOW AREN'T INTEGRATED WITH mpmath yet

In [30]:
def tridiagonal_matrix(n, a, b, c):
    M = np.zeros((n, n))
    # print(f'shape a = {a.shape}, shape b = {b.shape}, c shape = {c.shape}')
    for i in range(n):
        M[i][i] = b[i]
        if i > 0:
            M[i][i-1] = a[i]
        if i < n - 1:
            M[i][i+1] = c[i]

    return M


In [31]:
tridiagonal_matrix(20, np.ones((20, 1)), 2* np.ones((20, 1)),3* np.ones((20, 1)))

/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_59354/2901001217.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i] = b[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_59354/2901001217.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i+1] = c[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_59354/2901001217.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i-1] = a[i]


array([[2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [32]:
def make_matrix_e(q, vn):
    N = len(vn)
    h = vn[1]-vn[0]
    np_cos = np.frompyfunc(mp.cos, 1, 1)
    c = 2*q*np_cos(2* vn).reshape((len(vn),1))
    hm2 = np.ones((N,1))/(h*h)
    
    
    A = tridiagonal_matrix(N, hm2, -2*hm2-c, hm2)
    A[0,1] = 2*hm2[0]
    A[N-1,N-2] = 2*hm2[0]
    print(A)
    return A

In [33]:
vn = np.linspace(-np.pi, np.pi, 10)
make_matrix_e(-100.0,vn)

[[ 195.89649206    4.10350794    0.            0.            0.
     0.            0.            0.            0.            0.        ]
 [   2.05175397   30.6261276     2.05175397    0.            0.
     0.            0.            0.            0.            0.        ]
 [   0.            2.05175397 -192.04203209    2.05175397    0.
     0.            0.            0.            0.            0.        ]
 [   0.            0.            2.05175397 -104.10350794    2.05175397
     0.            0.            0.            0.            0.        ]
 [   0.            0.            0.            2.05175397  149.10538069
     2.05175397    0.            0.            0.            0.        ]
 [   0.            0.            0.            0.            2.05175397
   149.10538069    2.05175397    0.            0.            0.        ]
 [   0.            0.            0.            0.            0.
     2.05175397 -104.10350794    2.05175397    0.            0.        ]
 [   0.          

/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_59354/2901001217.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i] = b[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_59354/2901001217.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i+1] = c[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_59354/2901001217.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i-1] = a[i]
/var/folders/wt/zm67l5653nz4gjnqr_vx

array([[ 195.89649206,    4.10350794,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ],
       [   2.05175397,   30.6261276 ,    2.05175397,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    2.05175397, -192.04203209,    2.05175397,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    0.        ,    2.05175397, -104.10350794,
           2.05175397,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    0.        ,    0.        ,    2.05175397,
         149.10538069,    2.05175397,    0.        ,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    0.        ,    0.        ,    0.        ,
           2.05175397,  149.10538069,    2.05175397,    0

In [34]:
# make matrix e
from scipy import integrate


# def make_matrix_e(q, vn):
#     N = len(vn)
#     h = vn[1]-vn[0]
#     c = 2*q*np.array([np.cos(2* x) for x in vn])
#     hm2 = np.ones((N,1))/(h*h)
    
#     A = tridiagonal_matrix(N, hm2, -2*hm2-c, hm2)
#     A[0,1] = 2*hm2[0]
#     A[N-1,N-2] = 2*hm2[0]
#     return A

def mathieu_a(Ne, q, N):
    v = mp.linspace(-mp.pi, mp.pi, N)
    A = make_matrix_e(q,v)
    Draw, _ = eig(A)
    # print(len(Draw))
    Dreal = [val.real for val in Draw]
    Denum = list(enumerate(Dreal))
    Didx = sorted(Denum, key=lambda x: x[1], reverse=True)
    idx = [idx for idx, val in Didx]
    D = matrix(2*Ne, 1)
    for i in range(0,Ne):
        # Extract only even order eigenvalues.
        D[i] = -Dreal[idx[2*i]]

    return v, D

def mathieu_ce(Ne, q, N):
    
    v = np.linspace(-np.pi, np.pi, N)
    A = make_matrix_e(q,v)

    # print(f'A= {A}')
    Draw, Sraw = np.linalg.eig(A)
    # print(f'Sraw = {Sraw}')
    # print(f'D = {Draw}')
    Dreal = [val.real for val in Draw]

    Denum = list(enumerate(Dreal))
    Didx = sorted(Denum, key=lambda x: x[1], reverse=True)
    idx = [idx for idx, val in Didx]


    S = Sraw[:, idx]
    ce = S[:, :2*Ne:2]

    
    # Normalisation for the values when v = 0
    zidx = N // 2
    

    for j in range(Ne):
        if ce[zidx, j] < 0:
            ce[:, j] = - ce[:, j]
            

    # Normalisation 28.2.30
    # ce shape : (N, Ne)

    norm_cols = []
    h = v[1] -  v[0]


    # Normalisation for ce_n
    for j in range(ce.shape[1]):
        int_col = 0
        for i in range(1, ce.shape[0]):
            int_f_ij = (0.5) * ((ce[i - 1 , j])**2 + (ce[i, j])**2) * h
            int_col += int_f_ij
        traps_norm = sqrt(int_col / mp.pi) 
        norm_cols.append(traps_norm)
    
    
    for l in range(ce.shape[1]):
        ce[:, l] = ce[:, l] / norm_cols[l]
    
   

    # print(f'ce after norm= {ce}')



    return ce 


In [35]:
Ne = 3 # num of eigenvalues
Nq = 3  
q = np.linspace(0, 10, Nq)
N = 10  # discretisation of v
# mathieu_a(Ne, -100, N)
mathieu_ce(Ne, 1, N)

[[-6.10350794  4.10350794  0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 2.05175397 -4.45080429  2.05175397  0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          2.05175397 -2.2241227   2.05175397  0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          2.05175397 -3.10350794  2.05175397  0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          2.05175397 -5.63559682  2.05175397
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          2.05175397 -5.63559682
   2.05175397  0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          2.05175397
  -3.10350794  2.05175397  0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   2.05175397 -2.2241227   2.05175397  0.        ]
 [ 0.          0.          0.          0

/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_59354/2901001217.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i] = b[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_59354/2901001217.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i+1] = c[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_59354/2901001217.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i-1] = a[i]
/var/folders/wt/zm67l5653nz4gjnqr_vx

array([[ 0.35126076, -0.76143857,  1.04038613],
       [ 0.56754323, -0.81241288,  0.61415358],
       [ 1.02557421, -0.31775589, -0.81000575],
       [ 0.80744262,  0.73515874, -0.03893684],
       [ 0.40303421,  0.81158104,  0.82096793],
       [ 0.40303421,  0.81158104,  0.82096793],
       [ 0.80744262,  0.73515874, -0.03893684],
       [ 1.02557421, -0.31775589, -0.81000575],
       [ 0.56754323, -0.81241288,  0.61415358],
       [ 0.35126076, -0.76143857,  1.04038613]])

In [36]:
import numpy as np
import matplotlib.pyplot as plt

def write_mathieu_ce_gvs(q=None):
    """
    This creates a file with golden values in columns used
    to test other impls of the Mathieu ce fcns.
    
    Parameters:
    q : float, optional - if not provided, will prompt for input
    """
    
    if q is None:
        try:
            q = float(input("Enter q value: "))
        except ValueError:
            print("Invalid input for q")
            return
    
    print(f'q = {q:.6f}')
    
    N = 2500  # Number of v values
    # mathieu_ce only operates over the domain [-pi, pi]
    v = np.linspace(-mp.pi, mp.pi, N)
    Ne = 35    # Top order of fcn to request.
    
    
    Ss = mathieu_ce(Ne, q, N)  # GVs for different orders are
                                # arranged in columns.
   
    
    # Write GVs to a file along with the v value.
    filename = f'/Users/aliamy/Desktop/Mathieu/ScipyMathieuTesting/python_generated_gvs/python_mathieu_ce_gvs_q{q:.6f}.csv'
    
    with open(filename, 'w') as fh:
        # First write q value to file.
        fh.write(f'{q:14.10f}\n')
        
        # Then write fcn values.
        for i in range(len(v)):
            # Write v value followed by all function values for this v
            line = f'{v[i]}'
            for j in range(Ne):
                line += f', {Ss[i, j]}'
            line += '\n'
            fh.write(line)
    
    print(f'Golden values written to {filename}')

# Example usage:
if __name__ == "__main__":
    
    Q =  np.array([-100, -30, -10, -1, -0.1, -0.001, 0.001, 0.01, 0.1, 1, 10, 30, 100])
    # Q =  np.array([ 1])

    for q in Q:
        write_mathieu_ce_gvs(q)

    

/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_59354/2901001217.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i] = b[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_59354/2901001217.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i+1] = c[i]
/var/folders/wt/zm67l5653nz4gjnqr_vxcvnc0000gn/T/ipykernel_59354/2901001217.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M[i][i-1] = a[i]
/var/folders/wt/zm67l5653nz4gjnqr_vx

q = -100.000000
[[-316175.44658381  316375.44658381       0.         ...       0.
        0.               0.        ]
 [ 158187.72329191 -316175.44911245  158187.72329191 ...       0.
        0.               0.        ]
 [      0.          158187.72329191 -316175.45669829 ...       0.
        0.               0.        ]
 ...
 [      0.               0.               0.         ... -316175.45669829
   158187.72329191       0.        ]
 [      0.               0.               0.         ...  158187.72329191
  -316175.44911245  158187.72329191]
 [      0.               0.               0.         ...       0.
   316375.44658381 -316175.44658381]]
Golden values written to /Users/aliamy/Desktop/Mathieu/ScipyMathieuTesting/python_generated_gvs/python_mathieu_ce_gvs_q-100.000000.csv
q = -30.000000
[[-316315.44658381  316375.44658381       0.         ...       0.
        0.               0.        ]
 [ 158187.72329191 -316315.4473424   158187.72329191 ...       0.
        0.               